export const GAME_CONFIG = {
  difficultyMap: {
    1: ['easy'],
    2: ['easy', 'medium'],
  },
  questionsPerRound: 5,
  grandchildren: [
    { name: "Richie", folder: "richie", age: 10, emoji: "\u{1F9E1}" },
    { name: "Allison", folder: "allison", age: 8, emoji: "\u{1F338}" },
    { name: "Will", folder: "will", age: "almost 2", emoji: "\u{1F9E2}" },
  ],
  playerName: "Marion",
  questionsPerRound: 5,
  ttsEnabled: true,
  ttsRate: 0.95,
  fontSize: "normal",
  categoryWeights: {
    golden_age: 35,
    silver_screen: 20,
    name_that_show: 20,
    word_play: 15,
    everyday: 10,
  },
  subtitles: {
    appSubtitle: "A game just for Marion",
    letsPlay: "Let's Play!",
    newGame: "New Game",
    continue: "Continue",
    settings: "Settings",
    playAgain: "Play Again",
    youDidIt: "You Did It!",
    categoryNames: {
      golden_age: "Golden Age",
      silver_screen: "Silver Screen",
      name_that_show: "Name That Show",
      word_play: "Word Play",
      everyday: "Everyday World",
    },
    categoryIcons: {
      golden_age: "⭐",
      silver_screen: "\u{1F3AC}",
      name_that_show: "\u{1F4FA}",
      word_play: "\u{1F524}",
      everyday: "\u{1F30D}",
    },
    replayAudio: "Replay audio",
    back: "Back",
    ttsLabel: "Read Questions Aloud",
    fontSizeLabel: "Font Size",
    speechSpeedLabel: "Speech Speed",
    resetLabel: "Reset Progress",
    resetConfirm: "Are you sure?",
    resetYes: "Yes, Reset",
    resetNo: "No, Keep Playing",
    normal: "Normal",
    large: "Large",
    extraLarge: "Extra Large",
    slow: "Slow",
    normalSpeed: "Normal",
  },
}
